spring.application.name=testia-api
spring.data.mongodb.uri=mongodb://localhost:27017/testia
spring.data.mongodb.uuid-representation=standard
spring.data.mongodb.database=testia
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
spring.autoconfigure.exclude=\
com.openai.spring.OpenAISpringBootAutoConfiguration
openai.api.key=${OPENAI_API_KEY}
openai.model=gpt-5.1
groq_api_key=${GROQ_API_KEY}
brevo.api.key=${BREVO_API_KEY}
brevo.sender=testia.app@gmail.com  # o el correo que quieras
